name: Push to Docker registry

on:
   push:
     branches: master

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :alpine
        run: make build-alpine IMAGE_TAG=alpine

      - name: Deploy :alpine
        uses: actions-hub/docker@master
        with:
          args: push aoirint/transproxy:alpine
