name: Push to Docker registry

on:
   push:
     tags:
       - 'v*'

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :tag
        if: success()
        uses: actions-hub/docker@master
        with:
          args: build -t aoirint/transproxy:${IMAGE_TAG} ./docker/

      - name: Build :tag-node
        if: success()
        uses: actions-hub/docker@master
        with:
          args: build -t aoirint/transproxy:${IMAGE_TAG}-node --build-arg BASE_IMAGE=node:12 ./docker/

      - name: Build :node
        if: success()
        uses: actions-hub/docker@master
        with:
          args: build -t aoirint/transproxy:node --build-arg BASE_IMAGE=node:12 ./docker/

      - name: Build :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: build -t aoirint/transproxy:latest ./docker/

      - name: Deploy :tag
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/transproxy:${IMAGE_TAG}

      - name: Deploy :tag-node
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/transproxy:${IMAGE_TAG}-node

      - name: Deploy :node
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/transproxy:node

      - name: Deploy :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/transproxy:latest

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
